# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0
# https://github.com/bitnami/containers/blob/main/bitnami/mysql/docker-compose.yml

version: '3.8'

services:
  mysql:
    image: mysql:8.4
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      MYSQL_DATABASE: bk_store
      MYSQL_USER: bk_store_admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root_admin
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

volumes:
  mysql_data:
    driver: local